/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricity_bill_generation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sumit
 */
public class AdminDashboard extends javax.swing.JFrame {
private String ruid,rbillid,rusername;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        adduserwindow.setVisible(true);
        viewbillswindow.setVisible(false);
        addbillwindow.setVisible(false);
        viewuserswindow.setVisible(false);
        usercomplaintswindow.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addbillbtn = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        viewusersbtn = new javax.swing.JLabel();
        viewbillbtn = new javax.swing.JLabel();
        viewcomplaintsbtn = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        usercomplaintswindow = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usercomplaintstable = new javax.swing.JTable();
        viewbillswindow = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewbills = new javax.swing.JTable();
        viewuserswindow = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();
        addbillwindow = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        billno = new javax.swing.JLabel();
        enteruserid = new javax.swing.JTextField();
        submituseridbtn = new javax.swing.JButton();
        username1 = new javax.swing.JLabel();
        eusername = new javax.swing.JLabel();
        units1 = new javax.swing.JLabel();
        eunits = new javax.swing.JTextField();
        amount1 = new javax.swing.JLabel();
        eamount = new javax.swing.JTextField();
        duedate1 = new javax.swing.JLabel();
        eduedate = new javax.swing.JTextField();
        addubillbtn = new javax.swing.JButton();
        adduserwindow = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        meterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobileno = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        adduserbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricity_bill_generation/userdashlogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flash Electricity Suppliers");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(1, 1, 1));

        addbillbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbillbtn.setText("                   Add Bill");
        addbillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbillbtnMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                  Add User");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        viewusersbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        viewusersbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewusersbtn.setText("                 View Users");
        viewusersbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        viewusersbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewusersbtnMouseClicked(evt);
            }
        });

        viewbillbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        viewbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewbillbtn.setText("                  View Bill");
        viewbillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        viewbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbillbtnMouseClicked(evt);
            }
        });

        viewcomplaintsbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        viewcomplaintsbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewcomplaintsbtn.setText("            View Complaints");
        viewcomplaintsbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        viewcomplaintsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewcomplaintsbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addbillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewusersbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewbillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewcomplaintsbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(addbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewusersbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewcomplaintsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usercomplaintswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel24.setText("User Complaints");

        usercomplaintstable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usercomplaintstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usercomplaintstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usercomplaintstableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(usercomplaintstable);

        javax.swing.GroupLayout usercomplaintswindowLayout = new javax.swing.GroupLayout(usercomplaintswindow);
        usercomplaintswindow.setLayout(usercomplaintswindowLayout);
        usercomplaintswindowLayout.setHorizontalGroup(
            usercomplaintswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usercomplaintswindowLayout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(usercomplaintswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
        );
        usercomplaintswindowLayout.setVerticalGroup(
            usercomplaintswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usercomplaintswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewbillswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel23.setText("Bills");

        viewbills.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        viewbills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(viewbills);

        javax.swing.GroupLayout viewbillswindowLayout = new javax.swing.GroupLayout(viewbillswindow);
        viewbillswindow.setLayout(viewbillswindowLayout);
        viewbillswindowLayout.setHorizontalGroup(
            viewbillswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewbillswindowLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(viewbillswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        viewbillswindowLayout.setVerticalGroup(
            viewbillswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewbillswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        viewuserswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel22.setText("Users");

        userstable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userstable.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(userstable);

        javax.swing.GroupLayout viewuserswindowLayout = new javax.swing.GroupLayout(viewuserswindow);
        viewuserswindow.setLayout(viewuserswindowLayout);
        viewuserswindowLayout.setHorizontalGroup(
            viewuserswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewuserswindowLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(269, 269, 269))
            .addGroup(viewuserswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        viewuserswindowLayout.setVerticalGroup(
            viewuserswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewuserswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                .addContainerGap())
        );

        addbillwindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setText("Enter User ID:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel9.setText("Add Bill");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel10.setText("Bill No.");

        billno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        billno.setText("FB0001");

        enteruserid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        enteruserid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        enteruserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteruseridActionPerformed(evt);
            }
        });

        submituseridbtn.setBackground(new java.awt.Color(0, 0, 0));
        submituseridbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        submituseridbtn.setForeground(new java.awt.Color(255, 255, 255));
        submituseridbtn.setText("Submit");
        submituseridbtn.setActionCommand("User Login");
        submituseridbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        submituseridbtn.setFocusPainted(false);
        submituseridbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submituseridbtnActionPerformed(evt);
            }
        });

        username1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        username1.setText("User Name:");

        eusername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        eusername.setText("Sumit");

        units1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        units1.setText("Units:");

        eunits.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        eunits.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eunits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eunitsActionPerformed(evt);
            }
        });

        amount1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        amount1.setText("Amount:");

        eamount.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        eamount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eamountActionPerformed(evt);
            }
        });

        duedate1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        duedate1.setText("Due Date:");

        eduedate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        eduedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eduedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduedateActionPerformed(evt);
            }
        });

        addubillbtn.setBackground(new java.awt.Color(0, 0, 0));
        addubillbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        addubillbtn.setForeground(new java.awt.Color(255, 255, 255));
        addubillbtn.setText("Add Bill");
        addubillbtn.setActionCommand("User Login");
        addubillbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addubillbtn.setFocusPainted(false);
        addubillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addubillbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addbillwindowLayout = new javax.swing.GroupLayout(addbillwindow);
        addbillwindow.setLayout(addbillwindowLayout);
        addbillwindowLayout.setHorizontalGroup(
            addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbillwindowLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbillwindowLayout.createSequentialGroup()
                        .addComponent(submituseridbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbillwindowLayout.createSequentialGroup()
                        .addComponent(addubillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
            .addGroup(addbillwindowLayout.createSequentialGroup()
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addbillwindowLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addbillwindowLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(enteruserid, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(addbillwindowLayout.createSequentialGroup()
                                    .addComponent(units1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eunits, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(amount1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(eamount, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addbillwindowLayout.createSequentialGroup()
                                    .addComponent(username1)
                                    .addGap(18, 18, 18)
                                    .addComponent(eusername, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addbillwindowLayout.createSequentialGroup()
                                .addComponent(duedate1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eduedate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addbillwindowLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(billno, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbillwindowLayout.createSequentialGroup()
                    .addContainerGap(263, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(257, 257, 257)))
            .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addbillwindowLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(520, Short.MAX_VALUE)))
        );
        addbillwindowLayout.setVerticalGroup(
            addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbillwindowLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(billno)
                .addGap(26, 26, 26)
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(enteruserid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(submituseridbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username1)
                    .addComponent(eusername))
                .addGap(18, 18, 18)
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(units1)
                    .addComponent(eunits, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount1)
                    .addComponent(eamount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duedate1)
                    .addComponent(eduedate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(addubillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addbillwindowLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(473, Short.MAX_VALUE)))
            .addGroup(addbillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addbillwindowLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(jLabel10)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );

        adduserwindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel3.setText("Add User");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("UserName");

        username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Meter No");

        meterno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        meterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        meterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meternoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Mobile Number");

        mobileno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        mobileno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Password");

        adduserbtn.setBackground(new java.awt.Color(0, 0, 0));
        adduserbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        adduserbtn.setForeground(new java.awt.Color(255, 255, 255));
        adduserbtn.setText("Add User");
        adduserbtn.setFocusPainted(false);
        adduserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adduserwindowLayout = new javax.swing.GroupLayout(adduserwindow);
        adduserwindow.setLayout(adduserwindowLayout);
        adduserwindowLayout.setHorizontalGroup(
            adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserwindowLayout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adduserwindowLayout.createSequentialGroup()
                        .addGroup(adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(meterno, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adduserwindowLayout.createSequentialGroup()
                        .addComponent(adduserbtn)
                        .addGap(222, 222, 222))
                    .addGroup(adduserwindowLayout.createSequentialGroup()
                        .addGroup(adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adduserwindowLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(adduserwindowLayout.createSequentialGroup()
                                .addGroup(adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGap(34, 34, 34))))
        );
        adduserwindowLayout.setVerticalGroup(
            adduserwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adduserwindowLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(meterno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(adduserbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adduserwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addbillwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewuserswindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewbillswindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(usercomplaintswindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adduserwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(addbillwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewuserswindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewbillswindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(usercomplaintswindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(usercomplaintswindow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewbillswindow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewuserswindow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(addbillwindow, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(adduserwindow, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void meternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meternoActionPerformed

    private void mobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenoActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void adduserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserbtnActionPerformed
       String uname=username.getText().toString();
       String mno=meterno.getText().toString();
       String mobno=mobileno.getText().toString();
       String upass=password.getText().toString();
       if(uname.isEmpty())
       {
            JOptionPane.showMessageDialog(this, "Please Enter Username.",  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
       }
       else if(mno.isEmpty())
               {
                  JOptionPane.showMessageDialog(this, "Please Enter Meter Number.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);   
               }
       else if(mobno.isEmpty())
       {
          JOptionPane.showMessageDialog(this, "Please Enter Mobile Number.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);   
       }
       else if(upass.isEmpty())
       {
            JOptionPane.showMessageDialog(this, "Please Enter Password.",  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
       }
       else
       {
              getuid();
              String finaluid="FU00"+ruid;
             Connection con=null;
               con=dbconnection.con();
             try{
           String sql="INSERT INTO users VALUES('"+uname+"','"+upass+"','"+mobno+"','"+mno+"','"+finaluid+"')";
           String sql2="INSERT INTO users1 VALUES('"+finaluid+"','"+upass+"')";
           PreparedStatement pat=con.prepareStatement(sql);
         PreparedStatement  pat1=con.prepareStatement(sql2);
           pat.execute();
           pat1.execute();
           updateuid();
           JOptionPane.showMessageDialog(this, "User Added Successfully.\nUser ID: "+finaluid,  
                                   "Suceessfully", JOptionPane.INFORMATION_MESSAGE);
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
       }
               
       
    }//GEN-LAST:event_adduserbtnActionPerformed

    public void getuid()
{
    
try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from useridgen";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
            System.out.println("Id=" + rs.getString("id"));
          ruid=rs.getString("id");
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
}
    
    public void updateuid()
{
    try{
        Connection con=null;
          con=dbconnection.con();
      Statement st = null;
     st = con.createStatement();
     int newid=Integer.parseInt(ruid);
     int finalid=newid+1;
     String finalstr=String.valueOf(finalid);
     System.out.println(finalstr);
         String sqlUpdate = "UPDATE useridgen "
                + "SET id ='"+finalstr+"' "
                + "WHERE id = '"+ruid+"'";

PreparedStatement pstmt = con.prepareStatement(sqlUpdate);
pstmt.executeUpdate();
    }
    catch (Exception e) {
         e.printStackTrace();
      }

}
    
    public void getbillid()
    {
        try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from billidgen";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
            System.out.println("Id=" + rs.getString("id"));
          rbillid=rs.getString("id");
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
    }
    
    
     public void updatebillid()
{
    try{
        Connection con=null;
          con=dbconnection.con();
      Statement st = null;
     st = con.createStatement();
     int newid=Integer.parseInt(rbillid);
     int finalid=newid+1;
     String finalstr=String.valueOf(finalid);
     System.out.println(finalstr);
         String sqlUpdate = "UPDATE billidgen "
                + "SET id ='"+finalstr+"' "
                + "WHERE id = '"+rbillid+"'";

PreparedStatement pstmt = con.prepareStatement(sqlUpdate);
pstmt.executeUpdate();
    }
    catch (Exception e) {
         e.printStackTrace();
      }

}
    
    private boolean validate_uid(String username) {
        
        try{       
             Connection con=null;
      con=dbconnection.con();
       String sql="SELECT * FROM users where uid=?";
           PreparedStatement pst=con.prepareStatement(sql);
       pst.setString(1, username); 
       
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }
    }
    
      public void getusername()
    {
         try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from users where uid='"+enteruserid.getText().toString()+"'";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
            System.out.println("username=" + rs.getString("username"));
          rusername=rs.getString("username");
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
     
}
    
    private void enteruseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteruseridActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_enteruseridActionPerformed

    private void submituseridbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submituseridbtnActionPerformed
       
        if(validate_uid(enteruserid.getText().toString()))
     {
         username1.setVisible(true);
        eusername.setVisible(true);
        units1.setVisible(true);
        eunits.setVisible(true);
        amount1.setVisible(true);
        eamount.setVisible(true);
        duedate1.setVisible(true);
        eduedate.setVisible(true);
        addubillbtn.setVisible(true);
          getusername();
          eusername.setText(rusername);
        
        
        
        
        
        
     } else
     {
          username1.setVisible(false);
        eusername.setVisible(false);
        units1.setVisible(false);
        eunits.setVisible(false);
        amount1.setVisible(false);
        eamount.setVisible(false);
        duedate1.setVisible(false);
        eduedate.setVisible(false);
        addubillbtn.setVisible(false);
           JOptionPane.showMessageDialog(this, "Invalid User ID.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
   }        
    }//GEN-LAST:event_submituseridbtnActionPerformed

    private void eunitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eunitsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eunitsActionPerformed

    private void eamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eamountActionPerformed

    private void eduedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduedateActionPerformed

    private void addubillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addubillbtnActionPerformed
     String units=eunits.getText().toString();
       String amt=eamount.getText().toString();
       String duedate=eduedate.getText().toString();
       String billno1=billno.getText().toString();
       String userid=enteruserid.getText().toString();
       if(units.isEmpty())
       {
            JOptionPane.showMessageDialog(this, "Please Enter Username.",  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
       }
       else if(amt.isEmpty())
               {
                  JOptionPane.showMessageDialog(this, "Please Enter Meter Number.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);   
               }
       else if(duedate.isEmpty())
       {
          JOptionPane.showMessageDialog(this, "Please Enter Mobile Number.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);   
       }
      
       else
       {
            
             Connection con=null;
               con=dbconnection.con();
             try{
           String sql="INSERT INTO userbills VALUES('"+billno1+"','"+userid+"','"+units+"','"+amt+"','"+duedate+"','unpaid')";
           PreparedStatement pat=con.prepareStatement(sql);
           pat.execute();
           updatebillid();
           
           JOptionPane.showMessageDialog(this, "Bill Added Successfully",  
                                   "Suceessfully", JOptionPane.INFORMATION_MESSAGE);
           getbillid();
           billno.setText("FB00"+rbillid);
            username1.setVisible(false);
        eusername.setVisible(false);
        units1.setVisible(false);
        eunits.setVisible(false);
        amount1.setVisible(false);
        eamount.setVisible(false);
        duedate1.setVisible(false);
        eduedate.setVisible(false);
        addubillbtn.setVisible(false);
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
             getbillid();
       }
               

    }//GEN-LAST:event_addubillbtnActionPerformed

    private void addbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbillbtnMouseClicked
      getbillid();
        adduserwindow.setVisible(false);
        viewbillswindow.setVisible(false);
        addbillwindow.setVisible(true);
        viewuserswindow.setVisible(false);
        usercomplaintswindow.setVisible(false);
        billno.setText("FB00"+rbillid);
        username1.setVisible(false);
        eusername.setVisible(false);
        units1.setVisible(false);
        eunits.setVisible(false);
        amount1.setVisible(false);
        eamount.setVisible(false);
        duedate1.setVisible(false);
        eduedate.setVisible(false);
        addubillbtn.setVisible(false);
    }//GEN-LAST:event_addbillbtnMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         adduserwindow.setVisible(true);
        viewbillswindow.setVisible(false);
        addbillwindow.setVisible(false);
        viewuserswindow.setVisible(false);
        usercomplaintswindow.setVisible(false);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void viewusersbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewusersbtnMouseClicked
        adduserwindow.setVisible(false);
        viewbillswindow.setVisible(false);
        addbillwindow.setVisible(false);
        viewuserswindow.setVisible(true);
        usercomplaintswindow.setVisible(false);
        loadusers();
        
    }//GEN-LAST:event_viewusersbtnMouseClicked

    private void loadusers()
    {
        try{
            Connection con=null;
      con=dbconnection.con();
           String sql="select * from users";
           PreparedStatement pat=con.prepareStatement(sql);
          ResultSet rs= pat.executeQuery();
          userstable.setModel(DbUtils.resultSetToTableModel(rs));
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }
    
    private void loadbills()
    {
        try{
            Connection con=null;
      con=dbconnection.con();
           String sql="select * from userbills";
           PreparedStatement pat=con.prepareStatement(sql);
          ResultSet rs= pat.executeQuery();
          viewbills.setModel(DbUtils.resultSetToTableModel(rs));
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }
    
    private void loadcomplaints()
    {
        try{
            Connection con=null;
      con=dbconnection.con();
           String sql="select * from complaints";
           PreparedStatement pat=con.prepareStatement(sql);
          ResultSet rs= pat.executeQuery();
          usercomplaintstable.setModel(DbUtils.resultSetToTableModel(rs));
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }
    
    private void viewbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillbtnMouseClicked
          adduserwindow.setVisible(false);
        viewbillswindow.setVisible(true);
        addbillwindow.setVisible(false);
        viewuserswindow.setVisible(false);
        usercomplaintswindow.setVisible(false);
        loadbills();
    }//GEN-LAST:event_viewbillbtnMouseClicked

    private void viewcomplaintsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewcomplaintsbtnMouseClicked
          adduserwindow.setVisible(false);
        viewbillswindow.setVisible(false);
        addbillwindow.setVisible(false);
        viewuserswindow.setVisible(false);
        usercomplaintswindow.setVisible(true);
        loadcomplaints();
    }//GEN-LAST:event_viewcomplaintsbtnMouseClicked

    private void usercomplaintstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usercomplaintstableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usercomplaintstableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
                new AdminDashboard().setVisible(true);
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbillbtn;
    private javax.swing.JPanel addbillwindow;
    private javax.swing.JButton addubillbtn;
    private javax.swing.JButton adduserbtn;
    private javax.swing.JPanel adduserwindow;
    private javax.swing.JLabel amount1;
    private javax.swing.JLabel billno;
    private javax.swing.JLabel duedate1;
    private javax.swing.JTextField eamount;
    private javax.swing.JTextField eduedate;
    private javax.swing.JTextField enteruserid;
    private javax.swing.JTextField eunits;
    private javax.swing.JLabel eusername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField meterno;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField password;
    private javax.swing.JButton submituseridbtn;
    private javax.swing.JLabel units1;
    private javax.swing.JTable usercomplaintstable;
    private javax.swing.JPanel usercomplaintswindow;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username1;
    private javax.swing.JTable userstable;
    private javax.swing.JLabel viewbillbtn;
    private javax.swing.JTable viewbills;
    private javax.swing.JPanel viewbillswindow;
    private javax.swing.JLabel viewcomplaintsbtn;
    private javax.swing.JLabel viewusersbtn;
    private javax.swing.JPanel viewuserswindow;
    // End of variables declaration//GEN-END:variables
}
