/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricity_bill_generation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sumit
 */
public class UserDashboard extends javax.swing.JFrame {
private String userid,runits,rduedate,ramt;
    /**
     * Creates new form UserDashboard
     */
    public UserDashboard() {
        initComponents();
        
        allbillswindow.setVisible(true);
       changepasswindow.setVisible(false);
       paybillwindow.setVisible(false);
       raisecomplaintwindow.setVisible(false);
        seetransactionswindow.setVisible(false);
       auserid.setText(userid=SharedData.getUserID());
       getuserdata(auserid.getText().toString());
       loadbills();
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void getuserdata(String uid)
    {
        try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from users where uid='"+uid+"'";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
            System.out.println("Id=" + rs.getString("username"));
          ausername.setText(rs.getString("username"));
          ausermno.setText(rs.getString("meterno"));
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        auserid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ausername = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ausermno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        paybillbtn = new javax.swing.JLabel();
        viewbillbtn = new javax.swing.JLabel();
        seetransactionsbtn = new javax.swing.JLabel();
        complaintsbtn = new javax.swing.JLabel();
        changepassbtn = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        seetransactionswindow = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        transactionstable = new javax.swing.JTable();
        allbillswindow = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        allbillstable = new javax.swing.JTable();
        paybillwindow = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ebillno = new javax.swing.JTextField();
        paybill1btn = new javax.swing.JButton();
        tunitno = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        tduedate = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        tamt = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        tacno = new javax.swing.JTextField();
        e5 = new javax.swing.JLabel();
        tifsccode = new javax.swing.JTextField();
        ebillsubmitbtn = new javax.swing.JButton();
        raisecomplaintwindow = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tcomplaint = new javax.swing.JTextArea();
        raisecomplaintbtn = new javax.swing.JButton();
        changepasswindow = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        epass = new javax.swing.JTextField();
        echangepassbtn = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FU0001");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricity_bill_generation/userdashlogo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Flash Electricity Suppliers");

        auserid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        auserid.setForeground(new java.awt.Color(255, 255, 255));
        auserid.setText("FU0001");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User ID:");

        ausername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ausername.setForeground(new java.awt.Color(255, 255, 255));
        ausername.setText("Sumit Kuldharan");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name:");

        ausermno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ausermno.setForeground(new java.awt.Color(255, 255, 255));
        ausermno.setText("FM0001");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Meter No:");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(auserid, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ausername, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ausermno, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(auserid))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ausername)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ausermno))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(1, 1, 1));

        paybillbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        paybillbtn.setForeground(new java.awt.Color(255, 255, 255));
        paybillbtn.setText("                    Pay Bill");
        paybillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        paybillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paybillbtnMouseClicked(evt);
            }
        });

        viewbillbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        viewbillbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewbillbtn.setText("                  View Bills");
        viewbillbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        viewbillbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbillbtnMouseClicked(evt);
            }
        });

        seetransactionsbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        seetransactionsbtn.setForeground(new java.awt.Color(255, 255, 255));
        seetransactionsbtn.setText("             See Transactions");
        seetransactionsbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        seetransactionsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seetransactionsbtnMouseClicked(evt);
            }
        });

        complaintsbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        complaintsbtn.setForeground(new java.awt.Color(255, 255, 255));
        complaintsbtn.setText("                Complaints");
        complaintsbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        complaintsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                complaintsbtnMouseClicked(evt);
            }
        });

        changepassbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        changepassbtn.setForeground(new java.awt.Color(255, 255, 255));
        changepassbtn.setText("            Change Password");
        changepassbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        changepassbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changepassbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paybillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewbillbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seetransactionsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(complaintsbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(changepassbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(viewbillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(paybillbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(seetransactionsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(complaintsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(changepassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        seetransactionswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel27.setText("See Transactions");

        transactionstable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        transactionstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(transactionstable);

        javax.swing.GroupLayout seetransactionswindowLayout = new javax.swing.GroupLayout(seetransactionswindow);
        seetransactionswindow.setLayout(seetransactionswindowLayout);
        seetransactionswindowLayout.setHorizontalGroup(
            seetransactionswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seetransactionswindowLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addGroup(seetransactionswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        seetransactionswindowLayout.setVerticalGroup(
            seetransactionswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seetransactionswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLayeredPane1.add(seetransactionswindow, "card4");

        allbillswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel16.setText("All Bills");

        allbillstable.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        allbillstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(allbillstable);

        javax.swing.GroupLayout allbillswindowLayout = new javax.swing.GroupLayout(allbillswindow);
        allbillswindow.setLayout(allbillswindowLayout);
        allbillswindowLayout.setHorizontalGroup(
            allbillswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allbillswindowLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(allbillswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        allbillswindowLayout.setVerticalGroup(
            allbillswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allbillswindowLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLayeredPane1.add(allbillswindow, "card2");

        paybillwindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel17.setText("Pay Bill");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel18.setText("Enter Bill No.");

        ebillno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ebillno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ebillno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebillnoActionPerformed(evt);
            }
        });

        paybill1btn.setBackground(new java.awt.Color(0, 0, 0));
        paybill1btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        paybill1btn.setForeground(new java.awt.Color(255, 255, 255));
        paybill1btn.setText("Pay Bill");
        paybill1btn.setActionCommand("User Login");
        paybill1btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        paybill1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybill1btnActionPerformed(evt);
            }
        });

        tunitno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tunitno.setText("1000");

        e1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e1.setText("No of Units:");

        e2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e2.setText("Due Date:");

        tduedate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tduedate.setText("15-12-2020");

        e3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e3.setText("Total Amount:");

        tamt.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tamt.setText("500");

        e4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e4.setText("Enter Bank A/C No.");

        tacno.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tacno.setText(" ");
        tacno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tacno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacnoActionPerformed(evt);
            }
        });

        e5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        e5.setText("IFSC Code:");

        tifsccode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        tifsccode.setText(" ");
        tifsccode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tifsccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tifsccodeActionPerformed(evt);
            }
        });

        ebillsubmitbtn.setBackground(new java.awt.Color(0, 0, 0));
        ebillsubmitbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ebillsubmitbtn.setForeground(new java.awt.Color(255, 255, 255));
        ebillsubmitbtn.setText("Submit");
        ebillsubmitbtn.setActionCommand("User Login");
        ebillsubmitbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ebillsubmitbtn.setFocusPainted(false);
        ebillsubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebillsubmitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paybillwindowLayout = new javax.swing.GroupLayout(paybillwindow);
        paybillwindow.setLayout(paybillwindowLayout);
        paybillwindowLayout.setHorizontalGroup(
            paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paybillwindowLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paybillwindowLayout.createSequentialGroup()
                        .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(e1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paybillwindowLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paybillwindowLayout.createSequentialGroup()
                                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(paybillwindowLayout.createSequentialGroup()
                                        .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(paybillwindowLayout.createSequentialGroup()
                                                .addComponent(e3)
                                                .addGap(18, 18, 18)
                                                .addComponent(tamt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(paybillwindowLayout.createSequentialGroup()
                                                .addComponent(tunitno)
                                                .addGap(63, 63, 63)
                                                .addComponent(e2)
                                                .addGap(27, 27, 27)
                                                .addComponent(tduedate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(paybillwindowLayout.createSequentialGroup()
                                        .addComponent(ebillno, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(ebillsubmitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28))))
                    .addGroup(paybillwindowLayout.createSequentialGroup()
                        .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paybillwindowLayout.createSequentialGroup()
                                .addComponent(e5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tifsccode, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paybillwindowLayout.createSequentialGroup()
                                .addComponent(e4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tacno, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(paybillwindowLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(paybill1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paybillwindowLayout.setVerticalGroup(
            paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paybillwindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ebillno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ebillsubmitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(37, 37, 37)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tunitno)
                    .addComponent(tduedate)
                    .addComponent(e2)
                    .addComponent(e1))
                .addGap(36, 36, 36)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e3)
                    .addComponent(tamt))
                .addGap(29, 29, 29)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e4)
                    .addComponent(tacno, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paybillwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(e5)
                    .addComponent(tifsccode, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(paybill1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jLayeredPane1.add(paybillwindow, "card3");

        raisecomplaintwindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel28.setText("Raise Complaints");

        jLabel29.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel29.setText("Enter the Complaint:");

        tcomplaint.setColumns(20);
        tcomplaint.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tcomplaint.setRows(5);
        tcomplaint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(tcomplaint);

        raisecomplaintbtn.setBackground(new java.awt.Color(0, 0, 0));
        raisecomplaintbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        raisecomplaintbtn.setForeground(new java.awt.Color(255, 255, 255));
        raisecomplaintbtn.setText("Raise");
        raisecomplaintbtn.setActionCommand("User Login");
        raisecomplaintbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        raisecomplaintbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raisecomplaintbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout raisecomplaintwindowLayout = new javax.swing.GroupLayout(raisecomplaintwindow);
        raisecomplaintwindow.setLayout(raisecomplaintwindowLayout);
        raisecomplaintwindowLayout.setHorizontalGroup(
            raisecomplaintwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, raisecomplaintwindowLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(raisecomplaintwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(raisecomplaintwindowLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(raisecomplaintbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        raisecomplaintwindowLayout.setVerticalGroup(
            raisecomplaintwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(raisecomplaintwindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(raisecomplaintwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(raisecomplaintwindowLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel29))
                    .addGroup(raisecomplaintwindowLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(raisecomplaintbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jLayeredPane1.add(raisecomplaintwindow, "card5");

        changepasswindow.setBackground(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel30.setText("Change Password");

        jLabel31.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel31.setText("Enter New Password:");

        epass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        epass.setText(" ");
        epass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        epass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epassActionPerformed(evt);
            }
        });

        echangepassbtn.setBackground(new java.awt.Color(0, 0, 0));
        echangepassbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        echangepassbtn.setForeground(new java.awt.Color(255, 255, 255));
        echangepassbtn.setText("Change Password");
        echangepassbtn.setActionCommand("User Login");
        echangepassbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        echangepassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                echangepassbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changepasswindowLayout = new javax.swing.GroupLayout(changepasswindow);
        changepasswindow.setLayout(changepasswindowLayout);
        changepasswindowLayout.setHorizontalGroup(
            changepasswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changepasswindowLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(changepasswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(epass, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(echangepassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        changepasswindowLayout.setVerticalGroup(
            changepasswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changepasswindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addGroup(changepasswindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epass, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(77, 77, 77)
                .addComponent(echangepassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        jLayeredPane1.add(changepasswindow, "card6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
       this.dispose();
       new UserLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ebillnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebillnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebillnoActionPerformed

    private void paybill1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybill1btnActionPerformed
      String bankno=tacno.getText().toString();
      String ifsccode=tifsccode.getText().toString();
       DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
             LocalDateTime now = LocalDateTime.now();  
             String aajkidate=dtf.format(now);
      if(bankno.isEmpty())
      {
           JOptionPane.showMessageDialog(this, "Please Enter Bank Account Number.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
      }
      else if(ifsccode.isEmpty())
      {
           JOptionPane.showMessageDialog(this, "Please Enter IFSC Code.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
      }
      else
      {
          Connection con=null;
               con=dbconnection.con();
             try{
           String sql="INSERT INTO transactions VALUES('"+auserid.getText().toString()+"','"+ausermno.getText().toString()+"','"+ebillno.getText().toString()+"','"+tunitno.getText().toString()+"','"+tduedate.getText().toString()+"','"+tamt.getText().toString()+"','"+bankno+"','"+ifsccode+"','"+aajkidate+"')";
           PreparedStatement pat=con.prepareStatement(sql);
           pat.execute();
          updatebillpaidstate();
           
           JOptionPane.showMessageDialog(this, "Bill Paid Successfully",  
                                   "Suceessfully", JOptionPane.INFORMATION_MESSAGE);
          
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
      }
    }//GEN-LAST:event_paybill1btnActionPerformed

    private void tacnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tacnoActionPerformed

    private void tifsccodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tifsccodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tifsccodeActionPerformed

     private boolean validate_uid(String username) {
        
        try{       
             Connection con=null;
      con=dbconnection.con();
       String sql="SELECT * FROM userbills where billno=?";
           PreparedStatement pst=con.prepareStatement(sql);
       pst.setString(1, username); 
       
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }
    }
    private void ebillsubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebillsubmitbtnActionPerformed
       if(validate_uid(ebillno.getText().toString()))
     {
         e1.setVisible(true);
        e2.setVisible(true);
        e3.setVisible(true);
        e4.setVisible(true);
        e5.setVisible(true);
        tunitno.setVisible(true);
        tduedate.setVisible(true);
        tamt.setVisible(true);
        tacno.setVisible(true);
        tifsccode.setVisible(true);
        paybill1btn.setVisible(true);
        getusebilldata();
        tunitno.setText(runits);
        tduedate.setText(rduedate);
        tamt.setText(ramt);
        
        
        
        
        
        
     } else
     {
          e1.setVisible(false);
        e2.setVisible(false);
        e3.setVisible(false);
        e4.setVisible(false);
        e5.setVisible(false);
        tunitno.setVisible(false);
        tduedate.setVisible(false);
        tamt.setVisible(false);
        tacno.setVisible(false);
        tifsccode.setVisible(false);
        paybill1btn.setVisible(false);
           JOptionPane.showMessageDialog(this, "Invalid Bill Number",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
   }        
    }//GEN-LAST:event_ebillsubmitbtnActionPerformed
 public void updatebillpaidstate()
{
    try{
        Connection con=null;
          con=dbconnection.con();
      Statement st = null;
     st = con.createStatement();
   
         String sqlUpdate = "UPDATE userbills "
                + "SET 	paymentstatus ='Paid' "
                + "WHERE billno = '"+ebillno.getText().toString()+"'";

PreparedStatement pstmt = con.prepareStatement(sqlUpdate);
pstmt.executeUpdate();
    }
    catch (Exception e) {
         e.printStackTrace();
      }

}
    private void raisecomplaintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raisecomplaintbtnActionPerformed
        String complaint=tcomplaint.getText().toString();
        if(complaint.isEmpty())
        {
             JOptionPane.showMessageDialog(this, "Please Enter Complaint.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
              Connection con=null;
               con=dbconnection.con();
             try{
                 DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
             LocalDateTime now = LocalDateTime.now();  
             String aajkidate=dtf.format(now);
           String sql="INSERT INTO complaints VALUES('"+auserid.getText().toString()+"','"+complaint+"','"+aajkidate+"')";
           PreparedStatement pat=con.prepareStatement(sql);
           pat.execute();
           
           
           JOptionPane.showMessageDialog(this, "Complaint Raised Successfully",  
                                   "Suceessfully", JOptionPane.INFORMATION_MESSAGE);
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
        }
    }//GEN-LAST:event_raisecomplaintbtnActionPerformed

    private void epassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_epassActionPerformed
 public void updatepassword()
{
    try{
        Connection con=null;
          con=dbconnection.con();
      Statement st = null;
     st = con.createStatement();
   
         String sqlUpdate = "UPDATE users "
                + "SET 	userpass ='"+epass.getText().toString()+"' "
                + "WHERE uid = '"+auserid.getText().toString()+"'";

PreparedStatement pstmt = con.prepareStatement(sqlUpdate);
pstmt.executeUpdate();

  String sqlUpdate1 = "UPDATE users1 "
                + "SET 	userpass ='"+epass.getText().toString()+"' "
                + "WHERE uid = '"+auserid.getText().toString()+"'";

PreparedStatement pstmt1 = con.prepareStatement(sqlUpdate1);
pstmt1.executeUpdate();

JOptionPane.showMessageDialog(this, "Password Changed Successfully",  
                                   "Error", JOptionPane.INFORMATION_MESSAGE); 
    }
    catch (Exception e) {
         JOptionPane.showMessageDialog(this, "Failed to change password.",  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
      }

}
    private void echangepassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_echangepassbtnActionPerformed
     String newpass=epass.getText().toString();
     if(newpass.isEmpty())
     {
          JOptionPane.showMessageDialog(this, "Please Enter the Password",  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
     }
     else
     {
         updatepassword();
     }
    }//GEN-LAST:event_echangepassbtnActionPerformed
 private void loadbills()
    {
        try{
            Connection con=null;
      con=dbconnection.con();
           String sql="select * from userbills where userid='"+auserid.getText().toString()+"'";
           PreparedStatement pat=con.prepareStatement(sql);
          ResultSet rs= pat.executeQuery();
          allbillstable.setModel(DbUtils.resultSetToTableModel(rs));
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }
    private void viewbillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbillbtnMouseClicked
         allbillswindow.setVisible(true);
       changepasswindow.setVisible(false);
       paybillwindow.setVisible(false);
       raisecomplaintwindow.setVisible(false);
        seetransactionswindow.setVisible(false);
        loadbills();
    }//GEN-LAST:event_viewbillbtnMouseClicked
   public void getusebilldata()
    {
         try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from userbills where billno='"+ebillno.getText().toString()+"'";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
          //  System.out.println("username=" + rs.getString("username"));
          runits=rs.getString("units");
          rduedate=rs.getString("duedate");
          ramt=rs.getString("amount");
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
     
}
    private void paybillbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paybillbtnMouseClicked
        allbillswindow.setVisible(false);
       changepasswindow.setVisible(false);
       paybillwindow.setVisible(true);
       raisecomplaintwindow.setVisible(false);
        seetransactionswindow.setVisible(false);
        e1.setVisible(false);
        e2.setVisible(false);
        e3.setVisible(false);
        e4.setVisible(false);
        e5.setVisible(false);
        tunitno.setVisible(false);
        tduedate.setVisible(false);
        tamt.setVisible(false);
        tacno.setVisible(false);
        tifsccode.setVisible(false);
        paybill1btn.setVisible(false);
        
    }//GEN-LAST:event_paybillbtnMouseClicked

    private void seetransactionsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seetransactionsbtnMouseClicked
         allbillswindow.setVisible(false);
       changepasswindow.setVisible(false);
       paybillwindow.setVisible(false);
       raisecomplaintwindow.setVisible(false);
        seetransactionswindow.setVisible(true);
        loadtransactions();
    }//GEN-LAST:event_seetransactionsbtnMouseClicked

    private void complaintsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_complaintsbtnMouseClicked
         allbillswindow.setVisible(false);
       changepasswindow.setVisible(false);
       paybillwindow.setVisible(false);
       raisecomplaintwindow.setVisible(true);
        seetransactionswindow.setVisible(false);
    }//GEN-LAST:event_complaintsbtnMouseClicked

    private void changepassbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changepassbtnMouseClicked
        allbillswindow.setVisible(false);
       changepasswindow.setVisible(true);
       paybillwindow.setVisible(false);
       raisecomplaintwindow.setVisible(false);
        seetransactionswindow.setVisible(false);
    }//GEN-LAST:event_changepassbtnMouseClicked
 private void loadtransactions()
    {
        try{
            Connection con=null;
      con=dbconnection.con();
           String sql="select * from transactions where userid='"+auserid.getText().toString()+"'";
           PreparedStatement pat=con.prepareStatement(sql);
          ResultSet rs= pat.executeQuery();
          transactionstable.setModel(DbUtils.resultSetToTableModel(rs));
           
       } 
       catch(Exception ex)
       {
           JOptionPane.showMessageDialog(this, ex,  
                                   "Error", JOptionPane.ERROR_MESSAGE); 
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable allbillstable;
    private javax.swing.JPanel allbillswindow;
    private javax.swing.JLabel auserid;
    private javax.swing.JLabel ausermno;
    private javax.swing.JLabel ausername;
    private javax.swing.JLabel changepassbtn;
    private javax.swing.JPanel changepasswindow;
    private javax.swing.JLabel complaintsbtn;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JTextField ebillno;
    private javax.swing.JButton ebillsubmitbtn;
    private javax.swing.JButton echangepassbtn;
    private javax.swing.JTextField epass;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton paybill1btn;
    private javax.swing.JLabel paybillbtn;
    private javax.swing.JPanel paybillwindow;
    private javax.swing.JButton raisecomplaintbtn;
    private javax.swing.JPanel raisecomplaintwindow;
    private javax.swing.JLabel seetransactionsbtn;
    private javax.swing.JPanel seetransactionswindow;
    private javax.swing.JTextField tacno;
    private javax.swing.JLabel tamt;
    private javax.swing.JTextArea tcomplaint;
    private javax.swing.JLabel tduedate;
    private javax.swing.JTextField tifsccode;
    private javax.swing.JTable transactionstable;
    private javax.swing.JLabel tunitno;
    private javax.swing.JLabel viewbillbtn;
    // End of variables declaration//GEN-END:variables
}
