/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electricity_bill_generation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sumit
 */
public class UserLogin extends javax.swing.JFrame {
private Connection con = null;
private String ruserpass;
    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
        con=dbconnection.con();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eusername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        uloginbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        epassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        jLabel1.setText("User Login");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("User ID");

        eusername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        eusername.setText("FU002");
        eusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        eusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eusernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Password");

        uloginbtn.setBackground(new java.awt.Color(0, 0, 0));
        uloginbtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        uloginbtn.setForeground(new java.awt.Color(255, 255, 255));
        uloginbtn.setText("Login");
        uloginbtn.setActionCommand("User Login");
        uloginbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        uloginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uloginbtnActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electricity_bill_generation/exitbtn.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        epassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        epassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(eusername, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(epassword, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(uloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(278, 278, 278))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(eusername, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(epassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(uloginbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void eusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eusernameActionPerformed

    private void uloginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uloginbtnActionPerformed
        String uname=eusername.getText().toString();
        String upass=epassword.getText().toString();
        
        if(validate_login(uname,upass))
     {
         /*getuserpass();
         System.out.print("user eneterd:"+upass);
         if(ruserpass.equals(epassword.getText().toString()))
         {
             
         
         }
         else{
              JOptionPane.showMessageDialog(this, "Invalid Username or Password.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
         } */  
        SharedData.setUserID(uname);
         
         this.dispose();
         new UserDashboard().show();
           JOptionPane.showMessageDialog(this, "Login Successfully.",  
                                    "Congratulations", JOptionPane.INFORMATION_MESSAGE);
     } else
     {
           JOptionPane.showMessageDialog(this, "Invalid Username or Password.",  
                                   "Error", JOptionPane.ERROR_MESSAGE);
   }     
    
    }//GEN-LAST:event_uloginbtnActionPerformed

     
    private boolean validate_login(String username,String upass) {
        
        try{           
       String sql="SELECT * FROM users1 where uid=? and userpass=?";
           PreparedStatement pst=con.prepareStatement(sql);
       pst.setString(1, username);
       pst.setString(2, upass);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next()) 
       {
           System.out.print("true");
           return true;   
           
       
       }else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }        
    }
    
    
      private boolean validate_pass(String pass) {
        
        try{           
       String sql="SELECT userpass FROM users where uid=?";
           PreparedStatement pst=con.prepareStatement(sql);
       pst.setString(1, pass); 
       ResultSet rs = pst.executeQuery();                        
       if(rs.next()) 
       {
           System.out.print("true");
           return true;   
           
       
       }else
           return false;            
   }
   catch(Exception e){
       e.printStackTrace();
       return false;
   }        
    }
    
     public void getuserpass()
{
    
try{
    Connection con=null;
      con=dbconnection.con();
 PreparedStatement ps = null;
      Statement st = null;
      ResultSet rs = null;
       String query = "select * from users where uid='"+eusername.getText().toString()+"'";
         st = con.createStatement();
         rs = st.executeQuery(query);
         while (rs.next()) {
            System.out.println("Id=" + rs.getString("userpass"));
          ruserpass=rs.getString("userpass");
            
         }
         
}
 catch (Exception e) {
         e.printStackTrace();
      }
}
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    this.dispose();
    new MainMenu().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField epassword;
    private javax.swing.JTextField eusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton uloginbtn;
    // End of variables declaration//GEN-END:variables
}
